/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/_auth/auth.reset-password'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/_main/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/': typeof MainIndexRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/': typeof MainIndexRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_main/': typeof MainIndexRoute
  '/_auth/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/auth/reset-password' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/auth/reset-password' | '/signup'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/login'
    | '/_main/'
    | '/_auth/auth/reset-password'
    | '/_auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/reset-password': {
      id: '/_auth/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
